### ISSUE TITLE
Looks great.. just one question

### ISSUE THREAD

**Issue by franklywatson** [TritonDataCenter/smartos_cookbooks#1]
So i provisioned a new node and used the knife bootstraps to get my SmartOS hosted chef instance on the roll. 

One small thing I had to change: my motd.erb blew up on a smartosplus64 due to the :dmi attributes not being present

<%= node[:dmi][:system][:product] %> (<%= node[:dmi][:system][:serial_number] %>)

So now I have a node up and chef'd and showing in hosted chef, I added a role and environment via the UI however the chef-client hasn't run again (even though I can see it in the process list and the service is running) 

[root@Joyent-JP ~]# svcs -H chef-client
online         22:29:01 svc:/application/management/chef-client:default

How i do get chef-client to re-run - I can't manually invoke it like I'm used to.. Is it perhaps just a path thing?

**Comment by franklywatson** [comment]
Also.. i just noticed that after my knife bootstrap the instance doesn't end up with anything in /etc/chef.. is that intended? I had expected to see the pems, client.rb etc from the completion of the bootstrap.

**Comment by benr** [comment]
The method used to re-run Chef Solo is to restart the chef-solo SMF service.  If the values for DMI aren't present it shouldn't cause a blowup, it should just omit them.  In SmartMachines that MOTD wouldn't work because SMBIOS isn't accessable.

As for the configuration being in /var/chef rather than /etc/chef, that is because on SmartOS /etc is not persistent.

Based on these questions I can assume that your using these cookbooks in a SmartMachine or SmartOS Zone... these are intended specifically for SmartOS global zones.
